# Install community packages.
choco install 7zip
choco install awscli
choco install azure-cli
choco install burp-suite-free-edition
choco install discord
choco install docker-cli
choco install file-converter
choco install firefox
choco install flameshot
choco install git
choco install googlechrome
choco install gpg4win
choco install hashcat
choco install javaruntime
choco install keepass
choco install microsoft-windows-terminal
choco install nmap
choco install nuget.commandline
choco install obsidian
choco install openjdk
choco install openvpn-connect
choco install postman
choco install python
choco install qflipper
choco install sysinternals
choco install systeminformer
choco install tor-browser
choco install visualstudio2019community
choco install visualstudio2022community
choco install vscode
choco install windows-sdk-10-version-2004-windbg
choco install wireguard
choco install wireshark

# Add RedWine as a priority source.
choco source add --name='RedWine' --source='https://ky4meru.github.io/RedWine/index.json' --priority='1'

# Install RedWine packages.
choco install abuseazureapipermissions
choco install adrecon
choco install adsearch
choco install az
choco install azurehound
choco install bloodhound-cli
choco install bloodyad
choco install bruteshark
choco install brutespray
choco install chisel
choco install domainpasswordspray
choco install dotnet-frameworks
choco install dumpaadsynccreds
choco install edrsilencer
choco install gitleaks
choco install gobuster
choco install godpotato
choco install gowitness
choco install juicypotato
choco install kerbrute
choco install krbrelay
choco install krbrelayup
choco install lapstoolkit
choco install lazagne
choco install ldapsearch-ad
choco install ligolo-ng
choco install mailsniper
choco install mangle
choco install microsoft-activation-scripts
choco install mimikatz
choco install msolspray
choco install naabu
choco install netexec
choco install nuclei
choco install petitpotam
choco install pipx
choco install powercat
choco install powerlurk
choco install powermad
choco install powersploit
choco install powerupsql
choco install printspoofer
choco install privesccheck
choco install psmapexec
choco install roguepotato
choco install rubeus
choco install rustscan
choco install safetykatz
choco install seatbelt
choco install shadowspray
choco install sharpdpapi
choco install sharpersist
choco install sharpexclusionfinder
choco install sharpgpoabuse
choco install sharphound
choco install sharpsccm
choco install sharpsystemtriggers
choco install sharpup
choco install sharpview
choco install sharpwmi
choco install snaffler
choco install spoolfool
choco install sqlrecon
choco install standin
choco install sweetpotato
choco install threatcheck
choco install tokenuniverse
choco install trufflehog
choco install watson
choco install whisker
choco install windows-update
choco install winpeas
choco install winpwn
choco install yara
choco install zaproxy