name: Publish packages

on:
  push:
    branches:
    - 'main'

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Build Chocolatey packages
      run: |
        $packages = Get-ChildItem ./packages -Directory -Name
        foreach ($package in $packages) {
          choco pack ./packages/$package/$package.nuspec --out ./packages/$package
        }

    - name: Push NuGet packages to GitHub
      run: |
        $packages = Get-ChildItem *.nupkg -Recurse
        foreach ($package in $packages) {
          nuget push $package.FullName -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -ApiKey ${{ secrets.GITHUB_TOKEN }}
        }