name: Pack and publish packages

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Install latest SleetExe from NuGet
        run: |
          nuget install SleetExe -ExcludeVersion -OutputDirectory tools

      - name: Build Chocolatey packages
        run: |
          $packages = Get-ChildItem ./packages -Directory -Name
          foreach ($package in $packages) {
            choco pack ./packages/$package/$package.nuspec --out ./packages/$package
          }

      - name: Checkout gh-pages into ./site/
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: site

      - name: Push packages to feed
        run: |
          $packages = Get-ChildItem *.nupkg -Recurse -ErrorAction SilentlyContinue
          if ($packages.Count -eq 0) {
            Write-Host "No .nupkg files found. Skipping push."
          } else {
            .\tools\SleetExe\tools\Sleet.exe push --config ./site/sleet.json --source RedWine $packages.FullName
          }

      - name: Validate feed (optional but recommended)
        run: |
          .\tools\SleetExe\tools\Sleet.exe validate --config ./site/sleet.json --source RedWine

      - name: Commit and push feed updates to gh-pages
        run: |
          cd site
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update feed for $env:GITHUB_SHA" || echo "Nothing to commit."
          git push origin gh-pages